let Alls = [
    {
        id: 1,
        genre: "Music Festival",
        name: "Movie on The Beach 2017",
        picture: "img/MovieOnTheBeach1.jpg",
        thumb: "img/MovieOnTheBeach.jpg",
        tags: "music",
        description: "Cha Am Beachfront Music Festival: Free! 5 for friends under the hottest party, Outlet, Boy Peach Makers, New Charoen Pura, Apiwat and Sarima Stamps, give the music and make fun of the shoot. Cha Am beach in the middle of the sea by the sea.",
    },
      {
        id: 2,
        genre: "Tourist Nature",
        name: "Krachai flower bloom",
        picture: "img/krachai.jpg",
        thumb: "img/krachai1.jpg",
        tags: "flower",
        description: "June to August of each year .please check the date and time again clearly At Pa Hin Ngam National Park Thephrodite National Park and Sai Thong National Park. Nong Bua Rawe District Chaiyaphum Province Exhibition Visit Krachiew flower field. OTOP products to view the land. Watch Bua Sawan and Lan Hin Ngam. 0 4485 7099, Chaiyaphum Provincial Administrative Organization Tel. 0 4481 1376. Tel. +66 4421 3666, +66 4421 3030",
    },

    {
        id: 3,
        genre: "Music Festival",
        name: "Single Festival 2017",
        picture: "img/single.jpg",
        thumb: "img/single1.jpg",
        tags: "music",
        description: "Singer's Biggest Festival in Thailand with SangSom Presents Single Festival 2017. On Date: June 24, 2560Time: 6pm onwards Venue: Challenger Hall 1, Impact Muang Thong Thani. Ticket price: single woman for only 599 Baht / male for only 699 Baht", 
    },
    {
       id: 4,
        genre: "Thai Traditional",
        name: "Diving traditions",
        picture: "img/diving.jpg",
        thumb: "img/diving1.jpg",
        tags: "traditional",
        description: "Time Period: Thailand Day or the 15th day of the tenth month (on September 20, 2017) Wat Phra That temple beat the devil. And Phuttha Buri Buddhist Park. Visit the procession of the Phra Phutthabat, worship the Maha Thamratha and the boat race at Wat Trai, the sacred dances at the temple, win the devil, the light show, the legendary carriage, the scuba dive, and the delicious food festival in Buddhism, Peshawar park .Contact us for more information:Old Town Hall of Phetchabun The front of the temple. Temple of the beaten devil. Phetchabun Municipality Call 0-5671-1007 ,TAT Office Phitsanulok Tel: 0-5525-2742-3, 0-5525-9907",  
    },
    {
       id: 5,
        genre: "Thai Traditional",
        name: "Chak Phra Traditional Ceremony",
        picture: "img/chakpra.jpg",
        thumb: "img/chakpra1.jpg",
        tags: "traditional",
        description: "Surat Thani Province is pleased to invite you to the Chak Phra Traditional Boat Festival - Long Boat Race, Surat Thani, Thailand on 4-5 October 2016 at the grounds near Wang Tai Hotel. And by the river Tapi River Dam. Surat Thani Activities at the festival, see the bush rhinoceros parade parade - Phanom Phra Phraya boat race. Demonstration of folk handicrafts and folk wisdom Fair from the store. Official Exhibit OTOP products Cheap Fair Trade International theme park, comedy and musical performances by many famous artists. For more information, please contact: Municipality of Surat Thani Tel: 077-28 2614, TAT Surat Thani Office Phone number 077-28 8817 - 9",  
    },  
    {
       id: 6,
        genre: "Tourist Nature",
        name: "Flora Park.",
        picture: "img/florapark2.jpg",
        thumb: "img/florapark1.jpg",
        tags: "flower",
        description: "Embrace the cold winter weather at Flora Park. Life is BLOSSOM HERE ... embrace the cold wind. Inhale oxygen to fill the lungs In the garden of over 30,000 flowers in the sky at Flora Park (Flora Park) this year visitors will see a variety of wood. Including over 200 English Rose and many beautiful Landmark area around the area. Visitors can also buy products from farms, OTOP products and agricultural products of Wang Nam Khiao district. At a reasonable price.",  
    },  
    {
       id: 7,
        genre: "Tourist Nature",
        name: "Ordination parade on elephant’s back Festival",
        picture: "img/chank2.jpg",
        thumb: "img/chank1.jpg",
        tags: "elephant",
        description: "his competition is the largest and most exciting race in South East Asia and is a part of the Amazing Thailand Adventure Race Championship Series. For its 11th edition, will start and finish near the world famous bridge over the River Kwai and a special one as it will be the 11th anniversary with an expected attendance of 200 teams from around the world. Three to eight hours of wilderness adventure racing, will consist of teams of two racing through mountain biking, swimming and kayaking. And this year is a special one as it will be the 11th anniversary with an expected attendance of 200 teams from around the world. On May 2017, at Wat Chaeng Sawang, Surin",  
    },  
    {
       id: 8,
        genre: "Thai Traditional",
        name: "Attame Bucha Festival",
        picture: "img/attame2.jpg",
        thumb: "img/attame1.jpg",
        tags: "traditional",
        description: "We invite you to see sound and light shows and the re-enactment the funeral ceremony for the Lord Buddha ceremony, to wave the blankets for Phra That, to pay homage to Buddha relics, to give alms to Phra Asiti, to see performances on the stage and to shop at many booths.",  
    },  
];

export default Alls;
